[build]
  functions = "functions"
  command = "netlify-lambda install && npm run tsc"
[template.environment]
  BOT_TOKEN = "Telegram bot token here"
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/bot/:splat"
  status = 200
[functions]
  external_node_modules = ["mongodb"]
